---
title: "Lista 2 Multivariada"
author: "Davi Wentrick Feijó"
date: "2023-05-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Provar o seguinte teorema: Sejam $A$ e $B$ matrizes idempotentes. Então,
(a) $A + B$ é idempotente somente quando $AB = BA = 0$.

$$
(A + B)^2 = A + B
$$
$$
A^2 + AB + BA + B^2 = A + B
$$
Como $A$ e $B$ são idempotentes, temos $A^2 = A$ e $B^2 = B$. 

$$
A + AB + BA + B = A + B
$$
$$
AB + BA  = A + B - B - A 
$$
$$
AB + BA  = 0
$$

(b) $C = AB$ é idempotente somente quando $AB = BA$.

$$
C^2 = ABAB = AB
$$
Agora, queremos manipular essa equação para obter AB = BA. Para isso, podemos reescrever ABAB da seguinte forma
$$
ABAB = AB
$$
Se AB = BA podemos substituir na equação

$$
(AB)(BA) = AB \\
$$
$$
A(BB)A = ABA = AB \\
$$

Se AB = BA podemos substituir novamente na equação.Sabendo que A e B sao idempotentes!
$$
(AB)A= (BA)A = B(AA) = BA = AB \\
$$
Como $A$ e $B$ sao idempotentes, temos:
$$
A 
$$

Para essa equacao ser igual a zero temos duas opceos:
$$
AB = 0 \ \ \ \ \ \ AB - I = 0 \Rightarrow AB = I
$$



(c) $I - A$ é idempotente.

Temos que mostrar que:
$$
(I - A)^2 = I - A
$$
Vamos abrir o quadrado
$$
 I^2 - IA - AI + A^2 = I - A
$$

$$
 I - 2A + A^2 = I - A
$$
Como A é idempotente entao $A^2 = A$

$$
 I - 2A + A = I - A
$$
$$
 I - A = I - A
$$
Acabmos de mostrar que 

$$
(I - A)^2 = (I - A)
$$

### Provar o seguinte teorema: 

Seja $X(n×k)$ tal que $rank(X) = k < n$. Então, $P_X = X(X^tX)^{-1}X^t$ é idempotente e simétrica e consequentemente, uma matriz projeção ortogonal.


Vamos mostrat que é idempotente, para isso temos que mostrar que $(P_X)^2=P_X$
$$
(P_X)^2 = [X(X^tX)^{-1}X^t][X(X^tX)^{-1}X^t]
$$
$$
(P_X)^2 = X(X^tX)^{-1}X^tX(X^tX)^{-1}X^t
$$

$$
(P_X)^2 = X(X^tX)^{-1}[X^tX(X^tX)^{-1}]X^t
$$
$$
(P_X)^2 = X(X^tX)^{-1}IX^t = X(X^tX)^{-1}X^t = (P_X)
$$
Agora vamos mostrar que é simetrica. Uma matriz é simétrica se sua transposta é igual a ela mesma. Vamos mostrar que $(P_X)^T = P_X$.

$$
(P_X)^T = [X(X^TX)^{-1}X^T]^T
$$
$$
(P_X)^T = (X^T)[(X^TX)^{-1}]^TX^T
$$

$$
(P_X)^T = X^T[(X^TX)^{-1}]^TX
$$

